name: environment
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - cython
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - cupy
  - pytest
  - matplotlib
  - Pillow=8.0.0
  - cudatoolkit
  - cudnn
  - mkl
  - mkl-service
  - pytorch
  - tensorflow
  - tensorflow-gpu
  - tensorboard
  - tensorboard-plugin-wit
  - tensorflow-estimator
  - keras-base
  - keras-preprocessing
  - keras-applications
  - keras-gpu
  - opencv
  - flake8
  - coverage
  - typing-extensions
  - pyparsing
  - webencodings
  - ipython_genutils
  - jupyter_client
  - wcwidth
  - argon2-cffi
  - google-auth
  - gast
  - pandoc
  - freetype
  - jupyterlab_pygments
  - toml
  - notebook
  - pickleshare
  - kiwisolver
  - certifi
  - packaging
  - google-auth-oauthlib
  - idna_ssl
  - ca-certificates
  - iniconfig
  - attrs
  - icu
  - tornado
  - requests-oauthlib
  - sip
  - protobuf
  - pyjwt
  - wrapt
  - tk
  - atomicwrites
  - intel-openmp
  - yaml
  - pluggy
  - pygments
  - opt_einsum
  - requests
  - zstd
  - nbformat
  - olefile
  - multidict
  - ipykernel
  - charset-normalizer
  - pyopenssl
  - libtiff
  - jinja2
  - pyzmq
  - grpcio
  - markdown
  - async_generator
  - importlib_metadata
  - idna
  - libprotobuf
  - zlib
  - brotlipy
  - pycparser
  - yarl
  - _tflow_select
  - pyasn1-modules
  - pyasn1
  - typing_extensions
  - defusedxml
  - parso
  - cachetools
  - google-pasta
  - blinker
  - six
  - pysocks
  - markupsafe
  - hdf5
  - mistune
  - prompt-toolkit
  - jupyter_core
  - pyqt
  - werkzeug
  - blas
  - cffi
  - colorama
  - py
  - aiohttp
  - astor
  - more-itertools
  - jsonschema
  - terminado
  - jpeg
  - testpath
  - nbclient
  - qt
  - oauthlib
  - click
  - setuptools
  - termcolor
  - cycler
  - cryptography
  - joblib
  - wheel
  - importlib-metadata
  - rsa
  - send2trash
  - entrypoints
  - pyrsistent
  - jedi
  - lz4-c
  - nest-asyncio
  - h5py
  - sqlite
  - decorator
  - pyyaml
  - backcall
  - nbconvert
  - pandocfilters
  - absl-py
  - zipp
  - libpng
  - pytz
  - async-timeout
  - xz
  - bleach
  - ipython
  - openssl
  - prometheus_client
  - python-dateutil
  - urllib3
  - traitlets
  - threadpoolctl
  - chardet
