name: environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cython
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - cupy
  - pytest
  - matplotlib
  - Pillow
  - cudatoolkit
  - cudnn
  - mkl
  - mkl-service
  - pytorch
  - tensorflow
  - tensorflow-gpu
  - tensorboard
  - tensorboard-plugin-wit
  - tensorflow-estimator
  - keras-base
  - keras-preprocessing
  - keras-applications
  - keras-gpu
  - opencv
  - flake8
  - coverage
  