# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application on ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build-ci]')"

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2.1.1
      with: 
        activate-environment: environment
        environment-file: environment.yaml
        python-version: 3.6.13
        auto-activate-base: false

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .  --count \
                  --select=E9,F63,F7,F82 \
                  --show-source \
                  --statistics \
                  --extend-exclude build,dist,LSTM/lstm_template.py,VariationalAutoEncoder/train_vae_template.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8  --count \
                --exit-zero \
                --max-line-length=127 \
                --statistics \
                --extend-exclude build,dist,LSTM/lstm_template.py,VariationalAutoEncoder/train_vae_template.py
                  
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
        coverage run -m pytest
        coverage xml
        
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage.xml # optional
        #flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: false # optional (default = false)
